2023-09-12 12:21:04,547 ERROR: Exception on /reset_password_request [GET] [in C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\app\routes.py", line 173, in reset_password_request
    return render_template('reset_password_resquest.html', title='Reset Password', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password_resquest.html
2023-09-12 13:13:23,688 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:46]
2023-09-13 08:28:24,416 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:52]
2023-09-13 09:01:52,025 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:52]
2023-09-13 09:48:29,539 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:52]
2023-09-13 14:31:20,107 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:74]
2023-09-13 15:42:13,614 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:74]
2023-09-14 11:07:17,860 INFO: Microblog startup [in C:\Users\AndreuSadurní\Documents\microblog\app\__init__.py:77]
2023-09-14 11:07:20,923 ERROR: Exception on /index [GET] [in C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\app\main\routes.py", line 18, in before_request
    db.session.commit()
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 554, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1202, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\event\attr.py", line 378, in __call__
    fn(*args, **kw)
  File "C:\Users\AndreuSadurní\Documents\microblog\app\models.py", line 30, in before_commit
    'delete': list(session.delete)
              ^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not iterable
2023-09-14 11:07:24,149 ERROR: Exception on /index [GET] [in C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\flask\app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\app\main\routes.py", line 18, in before_request
    db.session.commit()
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 554, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1202, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "C:\Users\AndreuSadurní\Documents\microblog\venv\Lib\site-packages\sqlalchemy\event\attr.py", line 378, in __call__
    fn(*args, **kw)
  File "C:\Users\AndreuSadurní\Documents\microblog\app\models.py", line 30, in before_commit
    'delete': list(session.delete)
              ^^^^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not iterable
